plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '7.0.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}
spotless {
    java {
        toggleOffOn()
        indentWithSpaces()
        removeUnusedImports()
    }
}

ext {
    versionPostgres = '42.7.3'
    versionOpenApi = '2.8.3'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'


    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${versionOpenApi}"
    implementation "org.postgresql:postgresql:${versionPostgres}"

    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.4'
    testImplementation 'org.testcontainers:postgresql:1.20.4'
//    implementation 'org.springframework.boot:spring-boot-starter-webflux'
//    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'
//    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
//    implementation 'io.r2dbc:r2dbc-postgresql'

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
