version: '3'

services:

  postgres:
    image: postgres:17.0-alpine
    volumes:
      - test-library-database:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: on-failure
    env_file:
      - ./.env
#  app:
#    build: .
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"

volumes:
  test-library-database:
